import type { Metadata } from "next";
import { Roboto } from "next/font/google"; // Import Roboto
import "./styles/index.scss";

const roboto = Roboto({
    // Define Roboto font
    variable: "--font-roboto",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={` ${roboto.variable}`}>{children}</body>
        </html>
    );
}
